"""PT-BR AI-tell dictionaries.

Portuguese LLM output has its own fingerprint, and it is not a translation of
the English one. The dominant tells are formal-register verbs and connectives
that a Brazilian writer would rarely stack ("outrossim", "ademais", "no que
tange a"), plus calques from English marketing copy ("robusto", "abrangente",
"impulsionar"). There is no PT-BR equivalent of the Kobak frequency study, so
this list is assembled from the same structural principles rather than from
measured frequency shifts, and it is smaller and more conservative on purpose.
"""

from __future__ import annotations

HARD_TELLS: dict[str, tuple[str, ...]] = {
    "outrossim": ("também", "além disso"),
    "ademais": ("além disso", "e"),
    "destarte": ("assim", "então"),
    "cerne": ("centro", "núcleo"),
    "escopo": ("alcance", "limite"),
    "vasta": ("grande", "ampla"),
    "vasto": ("grande", "amplo"),
    "primordial": ("essencial", "básico"),
    "imprescindível": ("necessário", "indispensável"),
    "supracitado": ("citado acima", "esse"),
    "aludido": ("citado", "esse"),
    "salutar": ("saudável", "bom"),
    "profícuo": ("produtivo", "útil"),
    "mister": ("necessário",),
    "consubstanciar": ("formar", "compor"),
    "vislumbrar": ("ver", "enxergar"),
    "alavancar": ("usar", "aproveitar", "impulsionar"),
    "alavancando": ("usando", "aproveitando"),
    "otimizar": ("melhorar", "ajustar", "afinar"),
    "potencializar": ("aumentar", "reforçar"),
    "impulsionar": ("empurrar", "acelerar", "puxar"),
    "revolucionar": ("mudar", "virar de cabeça para baixo"),
    "revolucionário": ("novo", "que muda o jogo"),
    "transformador": ("grande", "profundo"),
    "inovador": ("novo", "original"),
    "holístico": ("completo", "de ponta a ponta"),
    "sinergia": ("encaixe", "soma"),
    "paradigma": ("modelo", "padrão"),
    "cenário": ("situação", "quadro", "contexto"),
    "panorama": ("quadro", "visão geral"),
    "jornada": ("caminho", "processo"),
    "mergulhar": ("entrar", "olhar de perto"),
    "desvendar": ("descobrir", "abrir"),
    "desbravar": ("explorar", "abrir caminho"),
    "tecer": ("montar", "construir"),
    "fomentar": ("estimular", "incentivar"),
    "fomentando": ("estimulando", "incentivando"),
    "elucidar": ("explicar", "esclarecer"),
    "corroborar": ("confirmar", "apoiar"),
    "atrelado": ("ligado", "preso"),
    "multifacetado": ("de vários lados", "complicado"),
    "meticuloso": ("cuidadoso", "detalhista"),
    "meticulosamente": ("com cuidado", "de perto"),
    "inestimável": ("enorme", "que vale muito"),
    "inabalável": ("firme", "constante"),
    "ressoar": ("pegar", "fazer sentido"),
    "vibrante": ("animado", "movimentado"),
}

SOFT_TELLS: dict[str, tuple[str, ...]] = {
    "robusto": ("sólido", "firme", "confiável"),
    "robusta": ("sólida", "firme", "confiável"),
    "abrangente": ("completo", "amplo"),
    "crucial": ("central", "decisivo"),
    "fundamental": ("básico", "essencial"),
    "significativo": ("grande", "real"),
    "significativamente": ("bastante", "muito"),
    "relevante": ("importante", "que pesa"),
    "eficiente": ("rápido", "econômico"),
    "eficaz": ("que funciona", "efetivo"),
    "estratégico": ("planejado", "deliberado"),
    "aprimorar": ("melhorar", "afinar"),
    "garantir": ("assegurar", "não deixar faltar"),
    "utilizar": ("usar",),
    "utilizando": ("usando",),
    "possibilitar": ("permitir", "deixar"),
    "viabilizar": ("permitir", "tornar possível"),
    "insights": ("achados", "conclusões", "leitura"),
    "atualmente": ("hoje", "agora"),
    "diversos": ("vários", "muitos"),
    "diversas": ("várias", "muitas"),
}

DELETABLE_PHRASES: tuple[str, ...] = (
    "é importante notar que",
    "é importante destacar que",
    "é importante ressaltar que",
    "vale ressaltar que",
    "vale destacar que",
    "vale mencionar que",
    "cabe destacar que",
    "cabe ressaltar que",
    "não se pode negar que",
    "é fundamental entender que",
    "como todos sabemos,",
    "como sabemos,",
    "de modo geral,",
    "em linhas gerais,",
    "no fim do dia,",
    "dito isso,",
    "sendo assim,",
    "nesse sentido,",
    "nesse contexto,",
    "diante disso,",
    "como mencionado anteriormente,",
    "conforme mencionado,",
    "no mundo de hoje,",
    "nos dias de hoje,",
    "na era digital,",
)

PHRASE_REPLACEMENTS: dict[str, str] = {
    "com o objetivo de": "para",
    "com a finalidade de": "para",
    "a fim de": "para",
    "no que tange a": "sobre",
    "no que se refere a": "sobre",
    "com relação a": "sobre",
    "em relação a": "sobre",
    "devido ao fato de que": "porque",
    "pelo fato de que": "porque",
    "apesar do fato de que": "embora",
    "na eventualidade de": "se",
    "um grande número de": "muitos",
    "a grande maioria dos": "a maioria dos",
    "uma vasta gama de": "muitos tipos de",
    "uma ampla gama de": "muitos tipos de",
    "em conclusão": "",
    "em resumo": "",
    "concluindo": "",
    "para resumir": "",
    "em suma": "",
    "por fim, mas não menos importante": "por fim",
    "primeiramente e acima de tudo": "primeiro",
    "cada um e todos": "cada",
    "desempenha um papel crucial em": "move",
    "desempenha um papel fundamental em": "move",
    "desempenha um papel importante em": "move",
    "serve como um": "é um",
    "é um testemunho de": "mostra",
    "lançar luz sobre": "explicar",
    "abrir caminho para": "preparar",
    "de última geração": "mais atual",
    "melhores práticas": "o que funciona",
    "quando se trata de": "em",
    "olhar mais aprofundado": "olhada de perto",
}

OPENING_TRANSITIONS: tuple[str, ...] = (
    "além disso",
    "adicionalmente",
    "portanto",
    "consequentemente",
    "entretanto",
    "no entanto",
    "todavia",
    "contudo",
    "assim",
    "dessa forma",
    "desse modo",
    "por conseguinte",
    "posteriormente",
    "similarmente",
    "da mesma forma",
    "por outro lado",
    "como resultado",
    "dito isso",
    "notavelmente",
    "essencialmente",
    "fundamentalmente",
    "em particular",
    "especificamente",
    "em última análise",
    "de modo geral",
    "nesse sentido",
    "nesse contexto",
    "diante disso",
    "ou seja",
    "isto é",
)

ASSISTANT_REGISTER: tuple[str, ...] = (
    "ótima pergunta",
    "com certeza!",
    "claro!",
    "espero que isso ajude",
    "fique à vontade para",
    "me avise se",
    "neste artigo, vamos",
    "neste artigo vamos",
    "neste artigo, exploraremos",
    "este artigo explora",
    "ao final deste artigo",
    "vamos mergulhar",
    "vamos começar",
    "sem mais delongas",
    "como uma ia",
    "como alguém que",
)

# Portuguese has no English-style contractions; the register equivalent is
# collapsing preposition+article and dropping the clitic-heavy formal forms.
CONTRACTIONS: dict[str, str] = {
    "de o ": "do ",
    "de a ": "da ",
    "em o ": "no ",
    "em a ": "na ",
    "para o ": "pro ",
    "para a ": "pra ",
    "de este": "deste",
    "de esse": "desse",
    "de aquele": "daquele",
    "em este": "neste",
    "em esse": "nesse",
}

TRIPLE_RE = r"\b\w+,\s+\w+\s+e\s+\w+\b"

PASSIVE_AUX = ("é", "são", "foi", "foram", "era", "eram", "ser", "sendo", "sido")
