"""EN-US AI-tell dictionaries.

Sources for the word lists: corpus studies of post-ChatGPT frequency shifts
(Kobak et al. 2025 identified 280+ "excess words" in academic abstracts, with
"delve" up ~25x), plus the structural rule set popularised by llmstrip and the
nine-lever humanize skill. The lists are deliberately split by severity:

  HARD_TELLS      strong signal, remove essentially all of them
  SOFT_TELLS      elevated in AI text but genuinely used by humans; thin them
                  out rather than eliminate, because zero occurrences of a
                  common word is itself an anomaly
  DELETABLE_*     phrases that carry no information and can just go
"""

from __future__ import annotations

# Words whose post-2022 frequency spike is steep enough that a single
# occurrence in a 2000-word article is a measurable signal.
HARD_TELLS: dict[str, tuple[str, ...]] = {
    "delve": ("dig", "get", "look"),
    "delves": ("digs", "looks"),
    "delving": ("digging", "looking"),
    "leverage": ("use", "apply", "put to work"),
    "leveraging": ("using", "applying"),
    "leverages": ("uses", "applies"),
    "tapestry": ("mix", "blend"),
    "realm": ("field", "area", "world"),
    "landscape": ("field", "market", "picture"),
    "myriad": ("many", "countless", "plenty of"),
    "plethora": ("plenty", "a pile", "no shortage"),
    "seamless": ("clean", "smooth", "painless"),
    "seamlessly": ("cleanly", "smoothly", "without fuss"),
    "streamline": ("simplify", "cut down", "tighten"),
    "streamlined": ("simplified", "tightened", "trimmed"),
    "underscore": ("show", "highlight", "point to"),
    "underscores": ("shows", "highlights", "points to"),
    "pivotal": ("key", "central", "decisive"),
    "transformative": ("major", "big", "far-reaching"),
    "unlock": ("open up", "get at", "reach"),
    "unlocking": ("opening up", "getting at"),
    "harness": ("use", "tap", "put to work"),
    "harnessing": ("using", "tapping"),
    "elevate": ("raise", "lift", "improve"),
    "navigate": ("handle", "work through", "get through"),
    "navigating": ("handling", "working through"),
    "testament": ("sign", "proof"),
    "multifaceted": ("many-sided", "complicated"),
    "paradigm": ("model", "approach"),
    "synergy": ("overlap", "fit"),
    "cutting-edge": ("newest", "latest", "current"),
    "game-changer": ("big shift", "turning point"),
    "game-changing": ("major", "decisive"),
    "unprecedented": ("new", "without a real precedent"),
    "meticulous": ("careful", "exacting"),
    "meticulously": ("carefully", "closely"),
    "intricate": ("complicated", "fiddly", "detailed"),
    "intricacies": ("details", "fine points"),
    "nuanced": ("more complicated than that", "layered"),
    "holistic": ("whole-picture", "end-to-end"),
    "embark": ("start", "begin", "set out"),
    "foster": ("build", "encourage", "grow"),
    "fostering": ("building", "encouraging"),
    "bolster": ("strengthen", "back up", "shore up"),
    "spearhead": ("lead", "drive"),
    "resonate": ("land", "stick", "connect"),
    "resonates": ("lands", "sticks", "connects"),
    "profound": ("deep", "serious", "real"),
    "vibrant": ("lively", "busy", "active"),
    "invaluable": ("essential", "worth a lot"),
    "unwavering": ("steady", "constant"),
    "commendable": ("solid", "good"),
    "noteworthy": ("worth a look", "notable"),
    "keen": ("sharp", "close"),
    "adept": ("good at it", "skilled"),
}

# Elevated but legitimate. Thinned, not purged.
SOFT_TELLS: dict[str, tuple[str, ...]] = {
    "robust": ("solid", "sturdy", "dependable"),
    "comprehensive": ("complete", "thorough", "full"),
    "crucial": ("critical", "essential", "central"),
    "significant": ("large", "real", "meaningful"),
    "significantly": ("sharply", "a lot", "markedly"),
    "essential": ("necessary", "required"),
    "vital": ("necessary", "critical"),
    "innovative": ("new", "original", "inventive"),
    "efficient": ("quick", "lean", "economical"),
    "optimize": ("tune", "improve", "sharpen"),
    "optimization": ("tuning", "improvement"),
    "enhance": ("improve", "sharpen", "strengthen"),
    "enhanced": ("improved", "better", "stronger"),
    "utilize": ("use",),
    "utilizing": ("using",),
    "facilitate": ("help", "make easier", "enable"),
    "ensure": ("make sure", "guarantee"),
    "robustly": ("solidly", "firmly"),
    "insights": ("findings", "takeaways", "read on it"),
    "actionable": ("usable", "concrete"),
    "align": ("match", "line up"),
    "aligned": ("matched", "lined up"),
    "impactful": ("effective", "consequential"),
    "empower": ("let", "enable", "give people"),
    "ultimately": ("in the end", "finally"),
    "moreover": ("also", "and"),
    "notably": ("in particular",),
    "arguably": ("probably", "you could argue"),
}

# Filler that carries zero information. Deleted outright, with the following
# character re-capitalised where needed.
DELETABLE_PHRASES: tuple[str, ...] = (
    "it is important to note that",
    "it's important to note that",
    "it is worth noting that",
    "it's worth noting that",
    "it is worth mentioning that",
    "it should be noted that",
    "it is essential to understand that",
    "it is crucial to note that",
    "needless to say,",
    "as we all know,",
    "as you may know,",
    "at the end of the day,",
    "when it comes down to it,",
    "in the world of",
    "in the realm of",
    "generally speaking,",
    "broadly speaking,",
    "for all intents and purposes,",
    "the fact of the matter is that",
    "one thing is clear:",
    "make no mistake,",
    "let's be clear:",
    "let us be clear:",
    "that being said,",
    "with that being said,",
    "it goes without saying that",
    "as previously mentioned,",
    "as mentioned earlier,",
)

# Phrases replaced rather than dropped.
PHRASE_REPLACEMENTS: dict[str, str] = {
    "in order to": "to",
    "a myriad of": "many",
    "a plethora of": "plenty of",
    "in today's": "in the current",
    "in today's world": "right now",
    "in today's digital age": "right now",
    "due to the fact that": "because",
    "in spite of the fact that": "although",
    "for the purpose of": "to",
    "with regard to": "about",
    "in the event that": "if",
    "a large number of": "many",
    "a significant number of": "many",
    "the vast majority of": "most",
    "in conclusion": "",
    "in summary": "",
    "to summarize": "",
    "to sum up": "",
    "in essence": "",
    "first and foremost": "first",
    "last but not least": "finally",
    "each and every": "every",
    "various different": "different",
    "completely eliminate": "eliminate",
    "absolutely essential": "essential",
    "past history": "history",
    "future plans": "plans",
    "plays a crucial role in": "drives",
    "plays a key role in": "drives",
    "plays a vital role in": "drives",
    "serves as a": "is a",
    "is a testament to": "shows",
    "not only": "not just",
    "a wide range of": "many kinds of",
    "a wide variety of": "many kinds of",
    "state-of-the-art": "current best",
    "best practices": "what works",
    "deep dive": "close look",
    "dive deep into": "get into",
    "shed light on": "explain",
    "pave the way for": "set up",
    "the key takeaway is": "the point is",
    "when it comes to": "with",
}

# Sentence-initial connectives. AI opens sentences with these at roughly triple
# the human rate; the fix is usually a period and a fresh start.
OPENING_TRANSITIONS: tuple[str, ...] = (
    "furthermore",
    "moreover",
    "additionally",
    "consequently",
    "nevertheless",
    "nonetheless",
    "therefore",
    "thus",
    "hence",
    "accordingly",
    "subsequently",
    "similarly",
    "likewise",
    "conversely",
    "in addition",
    "in contrast",
    "on the other hand",
    "as a result",
    "that said",
    "importantly",
    "notably",
    "crucially",
    "ultimately",
    "overall",
    "indeed",
    "in essence",
    "in particular",
    "specifically",
    "essentially",
    "fundamentally",
)

# Chat-assistant register: openers and closers from RLHF, the single strongest
# 2026 signal according to the detection literature.
ASSISTANT_REGISTER: tuple[str, ...] = (
    "great question",
    "certainly!",
    "of course!",
    "absolutely!",
    "i hope this helps",
    "hope this helps",
    "let me know if",
    "feel free to",
    "in this article, we will",
    "in this article, we'll",
    "this article explores",
    "this article will explore",
    "by the end of this article",
    "let's dive in",
    "let's get started",
    "without further ado",
    "as an ai",
    "as someone who",
)

CONTRACTIONS: dict[str, str] = {
    "it is": "it's",
    "it has": "it's",
    "that is": "that's",
    "there is": "there's",
    "there are": "there're",
    "what is": "what's",
    "who is": "who's",
    "here is": "here's",
    "he is": "he's",
    "she is": "she's",
    "they are": "they're",
    "we are": "we're",
    "you are": "you're",
    "i am": "I'm",
    "we will": "we'll",
    "you will": "you'll",
    "they will": "they'll",
    "it will": "it'll",
    "i will": "I'll",
    "we have": "we've",
    "you have": "you've",
    "they have": "they've",
    "i have": "I've",
    "do not": "don't",
    "does not": "doesn't",
    "did not": "didn't",
    "is not": "isn't",
    "are not": "aren't",
    "was not": "wasn't",
    "were not": "weren't",
    "cannot": "can't",
    "can not": "can't",
    "could not": "couldn't",
    "would not": "wouldn't",
    "should not": "shouldn't",
    "will not": "won't",
    "have not": "haven't",
    "has not": "hasn't",
    "had not": "hadn't",
    "let us": "let's",
    "you would": "you'd",
    "they would": "they'd",
    "we would": "we'd",
}

# Rule-of-three parallel lists ("fast, cheap, and reliable") are an AI staple.
# Detected for scoring; breaking them up is left to the model.
TRIPLE_RE = r"\b\w+,\s+\w+,\s+and\s+\w+\b"

PASSIVE_AUX = ("is", "are", "was", "were", "been", "being", "be")
