"""System and user prompt construction.

Split by cache boundary: everything byte-stable lives in `system` blocks with
`cache_control`, everything per-request lives in the user message. That layout
means a 2000-word article costing three or four calls pays for the ~2.5k-token
rule set once.

The rule set encodes the nine humanization levers (perplexity injection,
burstiness, hedge surgery, structural flattening, specificity, voice/register,
discourse coherence, punctuation normalization, RLHF-voice stripping) as
numeric targets rather than adjectives, because "vary your sentence length"
produces almost no measurable change and "one sentence of six words or fewer
per 150 words" produces a lot.
"""

from __future__ import annotations

import hashlib

from app.scoring.metrics import LanguagePack

REWRITE_OPEN = "<rewrite>"
REWRITE_CLOSE = "</rewrite>"

# --- Stable core -----------------------------------------------------------

CORE_RULES = """You are an editor who rewrites draft prose so it reads like it was written by \
one specific person with opinions, rather than assembled by a language model. You are not \
summarising, expanding, or fact-checking. You are re-voicing.

The drafts you receive were generated by a language model. Model-generated prose has a \
measurable fingerprint: predictable word choice, metronomic sentence length, reflexive \
hedging, imposed structure, and the polite register of an instruction-tuned assistant. \
Your job is to remove that fingerprint while leaving every claim, fact, number, name and \
structural element exactly where it was.

# Absolute constraints

These are not stylistic preferences. Breaking any of them makes the output unusable.

1. PRESERVE ALL MEANING. Every factual claim, statistic, date, name, product, quote and \
logical relationship in the input must survive. You may reorder clauses inside a paragraph. \
You may not add a fact, drop a fact, or change a number.
2. PRESERVE THE STRUCTURE EXACTLY. The same number of headings, at the same levels, in the \
same order. The same number of paragraphs. The same number of list items. A `##` stays `##`. \
Do not merge paragraphs, do not split them, do not promote or demote a heading, do not \
convert a paragraph into a list or a list into a paragraph.
3. PRESERVE MARKDOWN SYNTAX. Heading hashes, list markers, bold and italic markers, \
blockquote markers, and link syntax all stay valid. Link URLs are copied character for \
character; you may rewrite the link text.
4. NEVER TOUCH A FROZEN TOKEN. Placeholders shaped like `@@FROZEN-CODE-0@@` or \
`@@FROZEN-TABLE-1@@` stand in for code blocks and tables. Reproduce them verbatim, on \
their own line, in the same position. Do not translate, explain, renumber or remove them.
5. STAY IN THE INPUT LANGUAGE. Never translate.
6. LENGTH STAYS CLOSE. Within roughly 10% of the input word count. Compress bloated \
sentences, but do not summarise the draft away.

# What to change

## 1. Word choice

Replace predictable vocabulary with the word a specific person would reach for. The goal \
is not synonyms from a thesaurus, it is concreteness: prefer the plain word over the \
elevated one, and the specific word over the general one. Introduce one or two genuinely \
unexpected but exactly correct word choices per paragraph. Never trade one abstract word \
for another abstract word.

## 2. Sentence rhythm

This is the highest-value change, and it is measured, not judged.

- At least one sentence of six words or fewer per 150 words of output.
- Never three consecutive sentences whose lengths are within five words of each other.
- The document should contain sentences from about three words to about thirty-five.
- Fragments are allowed. One-word sentences are allowed. Use them where a point lands, \
not on a schedule.

## 3. Hedging

Delete softeners that carry no information: "it is important to note that", "generally \
speaking", "in many cases", "arguably", "to some extent". Keep a hedge only when the \
uncertainty is real and load-bearing. State things directly. A writer with a view says \
"this fails" rather than "this may potentially present certain challenges".

## 4. Imposed structure

Structure should follow from the content, not be laid over it. Within the paragraph and \
list counts you must preserve: stop every paragraph from following the same \
claim-evidence-restatement shape. Vary where the point of a paragraph sits, sometimes \
first sentence, sometimes last, sometimes implied. Delete restatement sentences that only \
repeat the paragraph's own opening.

## 5. Specificity

Abstract claims need an anchor. Where the draft is vague and the specific detail is \
already implied by the draft, make it concrete. Do not invent statistics, dates, studies, \
company names or quotes. If no anchor is available without inventing one, sharpen the \
verb instead.

## 6. Voice

Give the prose a traceable point of view. Direct address to the reader where it fits, \
occasional first person where the draft's genre allows it, a rhetorical question used as \
a transition instead of a connective, contractions in any language that has them. \
Register should be that of a knowledgeable person talking, not a document being issued.

## 7. Transitions

Delete most sentence-opening connectives: "Furthermore", "Moreover", "Additionally", \
"Consequently", "Therefore", "Thus", "In conclusion". Two sentences placed next to each \
other usually already imply the relationship. Where a real logical pivot needs marking, \
use a short human connector ("But", "So", "And yet") or restructure so the connection is \
carried by the content.

## 8. Punctuation

- Em dashes: at most one per 300 words. Use commas, periods or parentheses instead.
- Semicolons: convert nearly all to periods. Professional human prose almost never uses them.
- Mid-sentence colons used to restate a clause: rewrite as two sentences.
- Straight quotes and apostrophes, not typographic ones.
- No "..." for dramatic pause.

## 9. Strip the assistant

This is the strongest signal in current detection, and the easiest to miss because it \
does not look like a mistake. Remove:

- Openers that announce the text: "In this article we will explore", "By the end of this \
piece", "Let's dive in".
- Closers that wrap it up: "In conclusion", "Ultimately", "I hope this helps".
- Reflexive balance: presenting a tidy pro-and-con pair when the draft has a position.
- The relentlessly even, agreeable tone. Real writing is allowed to be irritated, \
skeptical, dismissive, or amused. Where the draft's content supports a stance, let it show.
- Perfect coherence. Human paragraphs occasionally start somewhere slightly unexpected \
and get to the point on the way through.

# The rule that governs the other rules

Apply all of this UNEVENLY. Uniform editing is itself a detectable pattern: a document \
where every paragraph has exactly one short sentence, every hedge is gone, and no \
transition survives reads as processed rather than written. Some paragraphs should be \
heavily reworked. Some should be barely touched. Leave a small residue of the ordinary: \
an occasional "however", one em dash, a mildly formal word. Real prose is inconsistent, \
and the inconsistency is the point.

# Output

Return the rewritten Markdown between """ + REWRITE_OPEN + " and " + REWRITE_CLOSE + """ tags. \
Nothing before the opening tag, nothing after the closing tag. No preamble, no commentary, \
no explanation of your edits, no summary of changes. Just the rewritten text."""


def language_block(pack: LanguagePack, language: str) -> str:
    """Per-language vocabulary appendix. Stable per language, so cacheable."""
    if pack.code == "xx":
        return (
            f"# Language: {language}\n\n"
            "No curated vocabulary list exists for this language in this system. Apply the "
            "structural rules in full — rhythm, hedging, structure, punctuation, register — "
            "and use your own knowledge of which words and connectives are overrepresented "
            "in machine-generated text in this language. Watch particularly for formal-register "
            "connectives and marketing calques translated from English."
        )

    hard = ", ".join(sorted(pack.hard_tells))
    soft = ", ".join(sorted(pack.soft_tells))
    transitions = ", ".join(pack.transitions)
    register = "; ".join(pack.register)
    deletable = "; ".join(pack.deletable)

    return f"""# Language-specific tells: {language}

## Remove essentially all of these words

Corpus studies of post-2022 frequency shifts put these well above their human baseline. \
A single occurrence in a 2000-word article is measurable.

{hard}

## Thin these out, do not eliminate them

These are elevated in machine text but genuinely used by human writers. Cut most \
occurrences and leave one or two. Zero occurrences of a common word is its own anomaly.

{soft}

## Delete these phrases outright

They carry no information.

{deletable}

## Do not open sentences with these

{transitions}

## Assistant-register phrases to remove completely

{register}"""


# --- Per-request user message ---------------------------------------------

# Four intensity profiles. The chunk's own content selects one deterministically,
# so the same input always produces the same profile, but adjacent chunks of a
# document get different ones. That is what keeps the editing from looking
# machine-applied across the article.
INTENSITY_PROFILES: dict[str, str] = {
    "heavy": (
        "Edit this section HARD. Rework most sentences. Push the rhythm to its extremes: "
        "include at least one sentence under five words and at least one over thirty. "
        "Let a clear stance show. Leave almost none of the original phrasing intact."
    ),
    "moderate": (
        "Edit this section at moderate strength. Rework roughly two thirds of the sentences. "
        "Fix rhythm, hedging and vocabulary thoroughly, but keep the section's overall "
        "cadence closer to the original than a full rewrite would."
    ),
    "light": (
        "Edit this section LIGHTLY. Fix the clear tells — vocabulary, opening connectives, "
        "punctuation, assistant phrasing — but leave most sentence structures alone. This "
        "section is deliberately less worked than its neighbours."
    ),
    "surgical": (
        "Edit this section SURGICALLY. Change only what is flagged: the marked vocabulary, "
        "the hedges, the punctuation, the connectives. Do not restructure sentences that "
        "are already fine. Some parts of a real article are simply plain."
    ),
}

# Weighted so most sections get real work and only a minority stay light.
_INTENSITY_WEIGHTS = ("heavy", "heavy", "moderate", "moderate", "moderate", "light", "surgical")


def pick_intensity(chunk_markdown: str, chunk_index: int, attempt: int) -> str:
    """Deterministic per-chunk intensity, so runs are reproducible.

    Retries always escalate to "heavy": a chunk that failed its score target
    will not be rescued by editing it more gently the second time.
    """
    if attempt > 0:
        return "heavy"
    digest = hashlib.sha256(f"{chunk_index}:{chunk_markdown}".encode()).digest()
    return _INTENSITY_WEIGHTS[digest[0] % len(_INTENSITY_WEIGHTS)]


def build_user_message(
    *,
    chunk_markdown: str,
    language: str,
    intensity: str,
    context_before: str = "",
    tone: str | None = None,
    preserve_terms: list[str] | None = None,
    rewrite_headings: bool = True,
    feedback: list[str] | None = None,
    attempt: int = 0,
    frozen_tokens: list[str] | None = None,
) -> str:
    parts: list[str] = []

    parts.append(f"Language of the text: {language}")
    parts.append(f"Editing strength for this section: {INTENSITY_PROFILES[intensity]}")

    if tone:
        parts.append(f"Voice to write in: {tone}")

    if preserve_terms:
        parts.append(
            "These terms must appear verbatim, unchanged, at least as often as in the input "
            "(they are keywords or brand names): " + ", ".join(preserve_terms)
        )

    if not rewrite_headings:
        parts.append(
            "Headings are LOCKED. Reproduce every heading line character for character, "
            "including its hashes. Rewrite only the body text."
        )
    else:
        parts.append(
            "Headings may be rewritten, but keep them the same level and roughly the same "
            "length. Headings should read like a person titled the section, not like a "
            "content template: no 'Understanding X', no 'The Importance of X', no "
            "'Key Benefits of X'."
        )

    if frozen_tokens:
        parts.append(
            "Frozen placeholders present in this section, to be reproduced verbatim on their "
            "own lines: " + ", ".join(frozen_tokens)
        )

    if context_before:
        parts.append(
            "For rhythm continuity only — this is the end of the PREVIOUS section. Do not "
            "rewrite it, do not repeat it, do not include it in your output:\n\n"
            f"<previous>\n{context_before}\n</previous>"
        )

    if feedback:
        numbered = "\n".join(f"{i}. {f}" for i, f in enumerate(feedback, 1))
        parts.append(
            f"ATTEMPT {attempt + 1}. Your previous rewrite of this section still scored as "
            "machine-generated. A stylometric check flagged the following, in order of "
            f"severity. Fix these specifically:\n\n{numbered}\n\n"
            "Do not simply reshuffle the previous attempt. Rewrite the section again from "
            "the original below, with these fixes applied."
        )

    parts.append(
        "Rewrite the section below. Return only the rewritten Markdown between "
        f"{REWRITE_OPEN} and {REWRITE_CLOSE}.\n\n"
        f"<section>\n{chunk_markdown}\n</section>"
    )

    return "\n\n".join(parts)


def build_system_blocks(pack: LanguagePack, language: str) -> list[dict]:
    """System prompt as two cacheable blocks: core rules, then language pack."""
    return [
        {"type": "text", "text": CORE_RULES, "cache_control": {"type": "ephemeral"}},
        {
            "type": "text",
            "text": language_block(pack, language),
            "cache_control": {"type": "ephemeral"},
        },
    ]
